### ISSUE TITLE
support connect 2 or more database

### ISSUE THREAD

**Issue by jatous** [MarketSquare/Robotframework-Database-Library#102]
sometimes rf cases need query more than one database, but library only support connect one now.

**Comment by jerry57** [comment]
We could use help in coding this if you feel inclined to contribute?  I will try to review all pull requests as quickly as possible.

**Comment by bhirsz** [comment]
I see that #147 implements it nicely, and using the same approach as Selenium or Requests libraries are doing it. We would need to review the PR and we could use it for multiple connection support.

**Comment by bhirsz** [comment]
@amochin 
I have rebased and updated open PR. Since I had to switch from using 'ConnectionCache' to our own custom solution (just a dict with alias: connection map, which is easier to manage if we disconnect) we need to decide what to do in case of duplicated connections. Current implementation:

```
Connect To Database  # will connect as "default" alias
Connect To Database  # it will warn that we're overwriting not closed connection, and open new connection

Disconnect From Database  # close recently added connection
```

If someone needs two concurrent connection, he needs to set explicit alias:
```
Connect To Database  # will connect as "default" alias
Connect To Database  alias=other_conn
```

But maybe - for any reason - we want to allow for 2 concurrent connections with the same, default alias?
```
Connect To Database  # will connect as "default" alias
Connect To Database  # will connect as "default2" alias, and switch "current" connection to default2
Disconnect From Database  # disconnect default2 and switch current to default
Disconnect From Database  # disconnect default
```

I think it's not needed and it's better to be explicit (if you need two connections, define alias) but I want to be sure. It could be also changed in the future.

**Comment by amochin** [comment]
@bhirsz I prefer the solution:
> If someone needs two concurrent connection, he needs to set explicit alias

Don't see any good reason for allowing 2 concurrent connections with the same, default alias.
I think it'd make things too complicated.
