### ISSUE TITLE
Cx_Oracle: Encoding issue & setting client character set

### ISSUE THREAD

**Issue by timohuov** [MarketSquare/Robotframework-Database-Library#138]
Hello!
 
Ran into following problem trying to query from my database, where characters ä,ö,å were included.
 
DatabaseLibrary 1.2.4
Cx_Oracle 7.3.0
Issue with: connection_manager.py: Need of UTF-8 encoding with cx_oracle.
 
**Issue:**
Unable to query UTF-8 characte
```
*** Settings ***
Library DatabaseLibrary
 
*** Test Cases ***
Test encoding
Connect To Database    cx_Oracle    Database    User    Password    Host    Port              
${test}=  Query     select user From t_tabel where user = 'Järeä'
Should be equal   ${test[0][0]}         Järeä
```
Error: UnicodeEncodeError: 'ascii' codec can't encode character '\xc4' in position 2: ordinal not in range(128)
Test fails due to requirement of UTF-8 charset
 
**Request change in connection_manager.py**
Adding encoding option to the connection connection
```python
def connect_to_database(self, dbapiModuleName=None, dbName=None, dbUsername=None, dbPassword=None, dbHost=None, dbPort=None, dbEncoding=None, dbCharset=None, dbConfigFile="./resources/db.cfg"):
 
elif dbapiModuleName in ["cx_Oracle"]:
            dbPort = dbPort or 1521
            oracle_dsn =  db_api_2.makedsn(host=dbHost, port=dbPort, service_name=dbName)
            logger.info('Connecting using: %s.connect(user=%s, password=%s, dsn=%s, encoding=%s) ' % (dbapiModuleName, dbUsername, dbPassword, oracle_dsn, dbEncoding))
            self._dbconnection = db_api_2.connect(user=dbUsername, password=dbPassword, dsn=oracle_dsn, encoding=dbEncoding)
```
 
 
**Test after the change:**
```
*** Settings ***
Library DatabaseLibrary
 
*** Test Cases ***
Test encoding
Connect To Database    cx_Oracle    Database    User    Password    Host    Port          UTF-8     
${test}=  Query     select user From t_tabel where user = 'Järeä'
Should be equal   ${test[0][0]}         Järeä
```

**Comment by jerry57** [comment]
Could you please do a PR with these changes and tests?  I will try to review as quickly as possible and get merge in.

**Comment by amochin** [comment]
It looks like this issue is not relevant anymore, since UTF-8 is the default encoding in cx_Oracle starting from [version 8](https://cx-oracle.readthedocs.io/en/latest/release_notes.html#version-8-0-june-2020). It's also mentioned [here in the official docs](https://cx-oracle.readthedocs.io/en/latest/user_guide/globalization.html#setting-the-client-character-set).
Running a simple test (similar to the one in the issue description) works also fine with the last version of cx_Oracle (8.3.0).

Do you think there is still a need to implement the additional encoding params as suggested?

**Comment by amochin** [comment]
Closing as there is no reply on this.
