### ISSUE TITLE
Query result list contains pyodbc.Row instead of python tuples

### ISSUE THREAD

**Issue by touchedthecode** [MarketSquare/Robotframework-Database-Library#201]
According to the documentation of the keyword Query "...to query for the values that will be returned as a list of **tuples**.", but when using pyodbc the result list contains pyodbc.Row objects. They look exactly like tuples, but when comparing both, assertions fail (for example when using "Lists Should Be Equal" or "Should Be Equal").

I can easily fix this in my test with a python list comprehension like this:

```
${query_result} =    Evaluate    [tuple(row) for row in ${query_result}]
```

but I wanted to let you know, maybe you can fix this in the Library, or mention this in the docs so others don't stumble on this and waste an hour debugging :)

**Comment by bhirsz** [comment]
If there is no ``returnAsDict`` specified, DatabaseLibrary will return whatever given database module is returning by default. According to https://peps.python.org/pep-0249/ module implementing DB API 2.0 should return list of tuples - but I guess some of the modoules (like pyodbc) are more liberal and return list of objects like ``pyodb.Row``. 

We have two solutions here:

a) either forcefully convert output to tuples (which will fix issues like yours but may cause other issues if the objects can't be converted to Tuple or someone rely on module specific return type)
b) fix the docs to mention exact behaviour (something along ``.. to query for the values that will be returned. Type of the values depends on the database module used but it should be tuple-like.`` - but I'm bad at writing docs ;) )

I'm leaning forward b)

**Comment by amochin** [comment]
@touchedthecode Thanks for submitting the issue!

I believe, we shouldn't convert all results to tuples by default, because:
1. As mentioned above, somebody might indeed want to use the module specific types
2. It can introduce backwards incompatibility if somebody is already using module specific types
3. We'd dive into a rabbit hole of one more custom handling of DB behavior

We definitely should updated the docs, as you mentioned above in b)

From the other side, I can see the issue when using the comparisons like _Lists should be equal_.
@bhirsz what do you think about introducing an optional parameter ``force_return_tuples`` (default would be **False**) in the _Query_ keyword - and do explicit converting to tuples if requested?

**Comment by amochin** [comment]
You're right, with a new parameter you'd need to set the conversion explicitly anyway - and for this case the _returnAsDict_ is already enough.
Good, then we'll just update the docs here.
